# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85722a8d3aa2fc90de9f454f569495470f74ff51365d717a02ac9bef560243aa0a11b5d1a80a836a9591a50ff570e20bf64e7ebb666560af69f8d873de40eecd

test:
  secret_key_base: b6e58c9bc8a9ec818c2d6dd7c238b06b40bef9490cb5aad6496b0f97c48c9b57521334d75537190a856d983ab2aec3f5ac0c962f9c972f593693f7dd4ace66af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
